language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules
    - $HOME/.cache

install:
  - npm install

before_script:
  - git config user.email "travis@test.com"
  - git config user.name "Travis"

script:
  - npm test

notifications:
  email:
    on_success: never
    on_failure: change
